#####
# Example using own CA certificate
# Build:  docker build -f Dockerfile.operator -t operator-jvm:1.1.0-rhitca .
# Run:    docker run --rm operator-jvm:1.1.0-rhitca
#####
FROM quay.io/websitecd/operator-jvm:1.1.0

ARG CA_CERT_URL=https://password.corp.redhat.com/RH-IT-Root-CA.crt

USER root
RUN curl -k ${CA_CERT_URL} --create-dirs -o /usr/share/pki/ca-trust-source/anchors/website-cd-ca.crt && \
    update-ca-trust
USER 1001
