#####
# Example using own CA certificate
# Build:  docker build --build-arg TAG=1.1.1 --build-arg CA_CERT_URL=https://password.corp.redhat.com/RH-IT-Root-CA.crt -f Dockerfile.gitinit -t content-git-init:1.1.1-rhitca .
#####
ARG TAG=latest
FROM quay.io/websitecd/content-git-init:${TAG}

ARG CA_CERT_URL

USER root
RUN curl -k ${CA_CERT_URL} --create-dirs -o /usr/local/share/ca-certificates/website-cd-ca.crt && \
    update-ca-certificates
USER 1001
