kind: "Template"
apiVersion: "v1"
metadata:
  name: "website-content"
labels:
  template: "website-content"
parameters:
  - name: "ENV"
    description: "Environment"
    required: true
  - name: "NAME"
    description: "Name of deployment"
    value: "web"
    required: false
  - name: "GIT_SSL_NO_VERIFY"
    value: "false"
    required: false
  - name: "IMAGE_INIT"
    value: "quay.io/spaship/content-git-init"
    required: false
  - name: "IMAGE_HTTPD"
    value: "quay.io/spaship/httpd"
    required: false
  - name: "IMAGE_API"
    value: "quay.io/spaship/content-git-api"
    required: false
  - name: "IMAGE_INIT_VERSION"
    value: "1.3.0"
    required: false
  - name: "IMAGE_HTTPD_VERSION"
    value: "0.1.0"
    required: false
  - name: "IMAGE_API_VERSION"
    value: "1.3.0"
    required: false

objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}-content-${ENV}
      labels:
        website: ${NAME}
    spec:
#      type: NodePort
      ports:
        # Expose main container
        - port: 80
          targetPort: 8080
          name: http
        # Expose rest api
        - port: 8090
          name: http-api
      selector:
        app: ${NAME}-content-${ENV}
#  - kind: Route
#    apiVersion: route.openshift.io/v1
#    metadata:
#      name: web-content-api
#    spec:
#      port:
#        targetPort: 8090
#      tls:
#        termination: edge
#      to:
#        kind: Service
#        name: web-content-${ENV}
#        weight: 100
#      wildcardPolicy: None

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${NAME}-content-${ENV}
      website: ${NAME}
      labels:
        website: ${NAME}
    spec:
      selector:
        matchLabels:
          app: ${NAME}-content-${ENV}
      replicas: 1
      template:
        metadata:
          labels:
            app: ${NAME}-content-${ENV}
            website: ${NAME}
        spec:
          initContainers:
            # Init data
            - name: init
              image: "${IMAGE_INIT}:${IMAGE_INIT_VERSION}"
              imagePullPolicy: IfNotPresent       # Always / IfNotPresent
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: CONFIG_PATH
                  value: "/app/config/content-config-git.yaml"
                - name: TARGET_DIR
                  value: "/app/data"
                - name: GIT_SSL_NO_VERIFY
                  value: "${GIT_SSL_NO_VERIFY}"
              volumeMounts:
                - mountPath: "/app/config/"
                  name: content-init
                  readOnly: true
                - mountPath: "/app/data/"
                  name: data
          containers:
            # Main container to serve data
            - name: httpd
              image: "${IMAGE_HTTPD}:${IMAGE_HTTPD_VERSION}"
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  cpu: 500m
                  memory: 250Mi
              ports:
                - containerPort: 8080
              volumeMounts:
                # Dynamically generated
            # Side car container providing API
            - name: api
              image: "${IMAGE_API}:${IMAGE_API_VERSION}"
              imagePullPolicy: IfNotPresent     # Always / IfNotPresent
              livenessProbe:
                httpGet:
                  path: "/"
                  port: 8090
                initialDelaySeconds: 2
                failureThreshold: 10
                periodSeconds: 10
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 8090
                initialDelaySeconds: 2
                failureThreshold: 5
                periodSeconds: 10
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
                limits:
                  cpu: 100m
                  memory: 100Mi
              ports:
                - containerPort: 8090
              env:
                - name: APP_DATA_DIR
                  value: "/app/data/"
              volumeMounts:
                - mountPath: "/app/data/"
                  name: data
          volumes:
            - name: content-init
              configMap:
                name: ${NAME}-content-init-${ENV}
                items:
                  - key: "content-config-git.yaml"
                    path: "content-config-git.yaml"
            - name: data
              emptyDir: { }
